Task 1. Basic graph utilities
kirill-ivanov-a/formal-lang-course pull request #1
Opened 2021-09-04 16:31 UTC by kirill-ivanov-a

- graph description function implemented;
- function of writing a two cycles graph to a file implemented;
- unit tests added;
- workflow to run unit tests added.

2021-09-05 08:12 UTC, EgorOrachyov commented
- graph description function implemented;
- function of writing a two cycles graph to a file implemented;
- unit tests added;
- workflow to run unit tests added.

2021-09-05 08:23 UTC, EgorOrachyov requested changes
Добрый день. Для начала неплохо, я бы сказал, `80%` работы уже выполнено. Остались незначительные доработки:

- В `.github/workflows/tests.yml` в матрицу для запуска было бы хорошо добавить еще `windows-latest` для тестирования на Windows. Мы в задачах будем использовать только кросс-платформенные библиотеки, поэтому проблем не будет.
- Файл `project/basic_graph_utils.py` я бы переименовал во что-то более классическое `project/graph_utils.py`, поскольку в дальнейших задачах проект будет расширятся, и эти функции уже не будут базовыми
- `По количеству вершин в циклах и именам меток строить граф из двух циклов и сохранять его в указанный файл в формате DOT (использовать pydot)` видится как на самом деле две отдельные задачи: создание графа `И` сохранение в файл, поэтому было бы хорошо иметь две функции.
- Если будут новые функции, то необходимо чуть-чуть доработать тесты, чтобы протестировать новые функции по созданию и сохранению на диск графов

> Мой комментарий на русском языке, т.к. курс читается на русском языке.
> Если английский предпочтительнее, то можем вести работу на нем.
> Так что  этот аспект -- на твое усмотрение.

2021-09-06 08:21 UTC, EgorOrachyov commented
Обращаю внимание, что в задании требуется консольное приложение `Реализовать консольное приложение, предоставляющее перечисленные ниже возможности`. Поэтому:

-  в `project/__main__` необходимо реализовать это приложение, которое будет запускаться при вызове `python -m project`. 
- Требования классические - необходимо консольное приложение, которое принимает на вход аргументы, и сразу выполняет какую-то полезную работу. 
- Для обработки аргументов использовать `argparse`
- функциональность та, которая указана в задании, яля `-print-graph-info=graph-name`, `--gen-graph -params=.. -output=...` и т.д. Допускаются вольности.

2021-09-08 12:57 UTC, kirill-ivanov-a commented
Добрый день. Внес требуемые изменения. В папке `project` расположен `README.md` с информацией по запуску.

2021-09-08 13:20 UTC, EgorOrachyov approved these changes

2021-09-08 13:54 UTC, merged